################################################################################
#
# Description: This script defines the project pipeline - it specifys the 
#              execution orders for all the code in this repo using a series of 
#              actions.
#
# Author(s): M Green
# Date last updated: 31/01/2022
#
################################################################################

version: '3.0'

expectations:
  population_size: 100000

actions:
  
  # Extract data ----

  ## Cohort data
  extract_data:
    run: cohortextractor:latest generate_cohort --study-definition study_definition --index-date-range "2021-12-13 to 2022-01-24 by week" --output-dir=output/data --output-format=csv.gz
    outputs:
      highly_sensitive:
        cohort: output/data/input_*.csv.gz
  
  
  # Data processing ----

  ## Process data
  data_process:
    run: r:latest analysis/process/process_data.R
    needs: [extract_data]
    outputs:
      highly_sensitive:
        data: output/data/data_processed.rds
  
  ## Inclusion/exclusion flow chart
  flow_chart:
    run: r:latest analysis/descriptive/flow_chart.R
    needs: [data_process]
    outputs:
      moderately_sensitive:
        data: output/data/flowchart.csv

  ## Data properties     
  data_properties:
    run: r:latest analysis/descriptive/data_properties.R output/data/data_processed.rds output/data_properties
    needs: [data_process]
    outputs:
      moderately_sensitive:
        cohort: output/data_properties/data_processed*.txt
  
  




