################################################################################
#
# Description: This script defines the project pipeline - it specifys the 
#              execution orders for all the code in this repo using a series of 
#              actions.
#
# Author(s): M Green
# Date last updated: 11/02/2022
#
################################################################################

version: '3.0'

expectations:
  population_size: 100000

actions:
  
  # Extract data ----
  extract_data:
    run: cohortextractor:latest generate_cohort --study-definition study_definition --output-dir=output/data --output-format=csv.gz
    outputs:
      highly_sensitive:
        cohort: output/data/input.csv.gz
  
  
  # Data processing ----
  data_process:
    run: r:latest analysis/process/process_data.R
    needs: [extract_data]
    outputs:
      highly_sensitive:
        data: output/data/data_processed*.rds
  
  # Data summaries ----
  flow_chart:
    run: r:latest analysis/descriptive/flow_chart.R
    needs: [data_process]
    outputs:
      moderately_sensitive:
        data: output/data/flowchart.csv

  data_properties:
    run: r:latest analysis/descriptive/data_properties.R output/data/data_processed.rds output/data_properties
    needs: [data_process]
    outputs:
      moderately_sensitive:
        cohort: output/data_properties/data_processed*.txt
  
  
  # Report ----
  report_data:
    run: r:latest analysis/descriptive/coverage_report_data.R
    needs: [data_process]
    outputs:
      moderately_sensitive:
        tables: output/reports/coverage/table_*.csv




