################################################################################
#
# Description: This script defines the project pipeline - it specifys the 
#              execution orders for all the code in this repo using a series of 
#              actions.
#
# Author(s): M Green
# Date last updated: 15/02/2022
#
################################################################################

version: '3.0'

expectations:
  population_size: 100000

actions:
  
  # Extract data ----
  extract_data:
    run: cohortextractor:latest generate_cohort --study-definition study_definition --output-dir=output/data --output-format=csv.gz
    outputs:
      highly_sensitive:
        cohort: output/data/input.csv.gz
  
  # Data processing ----
  data_process:
    run: r:latest analysis/process/process_data.R
    needs: [extract_data]
    outputs:
      highly_sensitive:
        data: output/data/data_processed*.rds
  
  # Data summaries ----
  data_properties:
    run: r:latest analysis/descriptive/data_properties.R output/data/data_processed.rds output/data_properties
    needs: [data_process]
    outputs:
      moderately_sensitive:
        cohort: output/data_properties/data_processed*.txt
        
  # Sensitivity anslysis ----
  sa_symptomatic_test:
    run: r:latest -e 'rmarkdown::render("analysis/descriptive/sa_symptomatic_test.Rmd", knit_root_dir = "/workspace", output_dir="/workspace/output/coverage")'
    needs: [data_process]
    outputs:
      moderately_sensitive:
        html: output/coverage/sa_symptomatic_test.html
  
  # Report ----
  report_data:
    run: r:latest analysis/descriptive/coverage_report_data.R
    needs: [data_process]
    outputs:
      moderately_sensitive:
        redacted_tables: output/coverage/table_*.csv
        unredacted_tables: output/coverage/for-checks/table_*.csv
  
  # Variation by STP ----
  stp_report:
    run: r:latest -e 'rmarkdown::render("analysis/descriptive/mabs-and-abs-by-stp.Rmd", knit_root_dir = "/workspace", output_dir="/workspace/output/variation")'
    needs: [data_process]
    outputs:
      moderately_sensitive:
        html: output/variation/mabs-and-abs-by-stp.html
        
  # Obs vs exp ----
  obs_vs_exp_report:
    run: r:latest -e 'rmarkdown::render("analysis/descriptive/obs-vs-exp.Rmd", knit_root_dir = "/workspace", output_dir="/workspace/output/variation")'
    needs: [data_process]
    outputs:
      moderately_sensitive:
        html: output/variation/obs-vs-exp.html

  # Crude count of outcomes ----
  outcomes_report:
    run: r:latest -e 'rmarkdown::render("analysis/descriptive/crude_outcomes.Rmd", knit_root_dir = "/workspace", output_dir="/workspace/output/effectiveness/counts")'
    needs: [data_process]
    outputs:
      moderately_sensitive:
        html: output/effectiveness/counts/crude_outcomes.html
  
  




