################################################################################
#
# Description: This script defines the project pipeline - it specifys the 
#              execution orders for all the code in this repo using a series of 
#              actions.
#
# Author(s): M Green
# Date last updated: 31/01/2022
#
################################################################################

version: '3.0'

expectations:
  population_size: 100000

actions:
  
  # Extract data ----

  ## Cohort data
  extract_data:
    run: cohortextractor:latest generate_cohort --study-definition study_definition --output-dir=output/data --output-format=csv.gz
    outputs:
      highly_sensitive:
        cohort: output/data/input.csv.gz
  
  
  # Data processing ----

  ## Process data
  data_process:
    run: r:latest analysis/process/process_data.R
    needs: [extract_data]
    outputs:
      highly_sensitive:
        data: output/data/data_processed.rds
  
  ## Inclusion/exclusion flow chart
  flow_chart:
    run: r:latest analysis/descriptive/flow_chart.R
    needs: [data_process]
    outputs:
      moderately_sensitive:
        data: output/data/flowchart.csv

  ## Data properties     
  data_properties:
    run: r:latest analysis/descriptive/data_properties.R output/data/data_processed.rds output/data_properties
    needs: [data_process]
    outputs:
      moderately_sensitive:
        cohort: output/data_properties/data_processed*.txt
  
  
  # Report ----
  
  ## Data, figures and tables
  report_data:
    run: r:latest analysis/descriptive/coverage_report_data.R
    needs: [data_process]
    outputs:
      moderately_sensitive:
        table1: output/reports/coverage/tables/report_stats.csv
        table2: output/reports/coverage/tables/table_elig_treat*.csv
        table3: output/reports/coverage/tables/table_demo_clinc_breakdown*.csv
        table4: output/reports/coverage/tables/data_flowchart_non_elig_redacted.csv
        table5: output/reports/coverage/tables/high_risk_cohort_comparison*.csv
        table6: output/reports/coverage/tables/data_time_between_redacted.csv
        table7: output/reports/coverage/tables/cum_*.csv
        figure1: output/reports/coverage/figures/cum_treatment_*.png
        figure2: output/reports/coverage/figures/cum_eligiblity_plot.png
        figure3: output/reports/coverage/figures/cum_eligiblity_therapeutics_plot.png



